name: Swift

on: [push,pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild -project 'WaterRocketUI.xcodeproj' -scheme 'WaterRocketUI' -destinatiion 'platform=macOS' test
