name: Swift

on: [push,pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Preparing
      run: cd WaterRocketUI
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
